config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  #resource :boys
  resources :boys do
  	resources :girl_friends
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/boy.rb
class Boy < ApplicationRecord

	validates :first_name, 	:presence => true
	validates :last_name, 	:presence => true
	validates :email, 			:presence => true

	validates :email, 			:uniqueness => true

	validates :first_name, uniqueness: { scope: :last_name, message: "Boy Exists" }

	# before_save :reverse_email

	# after_initialize :reverse_email

	has_many :girl_friends, :dependent => :destroy

	#scope :all_boys, -> select("*")

	def full_name
		"#{first_name} #{last_name}"
	end

	def gravatar
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
	end

	private

	def reverse_email
		self.email = self.email.reverse unless self.email.blank?
	end

end

app/models/girl_friend.rb
class GirlFriend < ApplicationRecord

	validates :first_name, 	:presence => true
	validates :last_name, 	:presence => true
	validates :email, 			:presence => true

	validates :email, 			:uniqueness => true

	validates :first_name, uniqueness: { scope: :last_name, message: "Girl Friend Exists" }

	# before_save :reverse_email

	# after_initialize :reverse_email

	belongs_to :boy


	def full_name
		"#{first_name} #{last_name}"
	end

	def gravatar
		"http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(email)}"
	end

	private

	def reverse_email
		self.email = self.email.reverse unless self.email.blank?
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boys_controller.rb
class BoysController < ApplicationController


	before_action :find_boy, :only => [:show, :destroy, :edit, :update]

	#before_action :authorize, :except => [:index, :new, :create]

	def index
		@boys = Boy.all
	end

	def show
		if @boy.restricted
			redirect_to root_path, :notice => {:status => "error", :message => "Boy is Restricted"}
		end
	end

	def edit
		
	end

	def update
		update_boy_success = @boy.update(boy_params)

		respond_to do |format|
			format.html{
				if update_boy_success
					redirect_to root_path, :notice => {:status => "success", :message => "Successfully Updated Boy"}
				else
					redirect_to edit_boy_path, :notice => {:status => "error", :message => "Boy Updation Failed"}
				end
			}
		end
	end

	def new
		@boy = Boy.new
	end

	def create
		new_boy = Boy.new(boy_params)

		new_boy_success = new_boy.save

		respond_to do |format|
			format.html{
				if new_boy_success
					redirect_to root_path, :notice => {:status => "success", :message => "Successfully Created New Boy"}
				else
					redirect_to new_boy_path, :notice => {:status => "error", :message => "New Boy Creation Failed"}
				end
			}
		end
	end

	def destroy
		if @boy.destroy!
			redirect_to root_path, :notice => {:status => "success", :message => "Successfully Deleted"}
		else
			redirect_to root_path, :notice => {:status => "error", :message => "Deletion Failed"}
		end
	end

	private

	def find_boy
		@boy = Boy.find(params[:id].to_i)
	end

	def boy_params

		#params[:boy][:restricted] = false unless params[:boy][:restricted].present?
		params.require(:boy).permit(:first_name, :last_name, :email)
	end

end

app/controllers/girl_friends_controller.rb
class GirlFriendsController < ApplicationController

	before_action :find_girl_friend, :only => [:show, :destroy, :edit, :update]

	before_action :find_boy

	def new
		@girl_friend = GirlFriend.new
	end

	def show

	end

	def edit

	end

	def create
		new_girl_friend = @boy.girl_friends.new(girl_friend_params)

		new_new_girl_friend_success = new_girl_friend.save

		respond_to do |format|
			format.html{
				if new_new_girl_friend_success
					redirect_to boy_path(@boy.id), :notice => {:status => "success", :message => "Successfully Created New Girl Friend"}
				else
					redirect_to new_boy_girl_friend_path(@boy.id), :notice => {:status => "error", :message => "New Girl Friend Creation Failed"}
				end
			}
		end
	end


	def destroy
		if @girl_friend.destroy!
			redirect_to boy_path(@boy.id), :notice => {:status => "success", :message => "Girl Friend Successfully Deleted"}
		else
			redirect_to boy_path(@boy.id), :notice => {:status => "error", :message => "Girl Friend Deletion Failed"}
		end
	end

		def update
		update_gf_success = @girl_friend.update(girl_friend_params)

		respond_to do |format|
			format.html{
				if update_gf_success
					redirect_to boy_path(@boy.id), :notice => {:status => "success", :message => "Successfully Updated Girl Friend"}
				else
					redirect_to edit_boy_girl_friend_path, :notice => {:status => "error", :message => "Girl Friend Updation Failed"}
				end
			}
		end
	end

	private

	def find_boy
		@boy = Boy.find(params[:boy_id].to_i)
	end

	def find_girl_friend
		@girl_friend = GirlFriend.find(params[:id].to_i)
	end

	def girl_friend_params
		params.require(:girl_friend).permit(:first_name, :last_name, :email)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boys_helper.rb
module BoysHelper
end

app/helpers/girl_friends_helper.rb
module GirlFriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boys/_form.html.erb
	<%= form_for(@boy,:html => {:class => "form-horizontal"}) do %>
	    <div class="form-group">
	      <label class="control-label col-sm-2" for="email">First Name:</label>
	      <div class="col-sm-10">
	      	<input type="text" class="form-control" id="first_name" placeholder="Enter First Name" name="boy[first_name]" value="<%= @boy.first_name %>" required>

	      </div>
	    </div>

	    <div class="form-group">
	      <label class="control-label col-sm-2" for="email">Last Name:</label>
	      <div class="col-sm-10">
	      	<input type="text" class="form-control" id="last_name" placeholder="Enter Last Name" name="boy[last_name]" value="<%= @boy.last_name %>" required>
	      </div>
	    </div>

	    <div class="form-group">
	      <label class="control-label col-sm-2" for="pwd">Email:</label>
	      <div class="col-sm-10">          
	        <input type="email" class="form-control" id="email" placeholder="Enter email" name="boy[email]" value="<%= @boy.email %>" required>
	      </div>
	    </div>

	    <div class="form-group">        
	      <div class="col-sm-offset-2 col-sm-10">
	        <button type="submit" class="btn btn-success">Submit</button>
	        <a href="<%= url_for(:back) %>" class="btn btn-danger"> Cancel
				  </a>
	      </div>
	    </div>
<% end %>

app/views/boys/edit.html.erb
<div class="container">
<h1 class = "boy_head"> Edit Boy </h1>

<%= render :partial => 'form' %>
</div>

<style type="text/css">
	h1.boy_head{
		border-bottom: 3px solid brown;
		color: wheat;
	}
	
</style>

app/views/boys/index.html.erb
<div class="container">
<h1 class = "boy_head"> Boys List </h1>


<p style="float: right;">

  <a href="<%= new_boy_path() %>" class="btn btn-info btn-sm">
    <span class="glyphicon glyphicon-user"></span> New Boy 
  </a>
</p> 
  <div class="container" style="overflow: auto;">
    
    <div class="row">  

    	<% @boys.each do |boy| %>
				
				<div class="col-sm-4 blurred-bg" style="border-left: 3px solid gray;margin-bottom: 15px;">
				
	        <h3><%= boy.full_name%></h3>
	        <div class="col-sm-2">
	        <img src="<%= boy.gravatar %>" class="img-rounded" alt="Cinque Terre" width="75" height="75">
	        </div>
	        <div class="col-sm-10">
	        <ul>
	        	<li><label>Email:</label><span class="boyspan" ><%= boy.email%> <span></span></li>
	        	<li><label>Number of GF:</label> <span class="boyspan"><%= boy.girl_friends.length%></span></li>
	        </ul>
	        </div>

	         <div class="col-sm-12" style="margin-top: 15px;">
	       	<%= link_to "Show Details", boy_path(boy.id) ,:class => "btn btn-success btn-xs action-button" %>
	       	<%= link_to "Edit Details", edit_boy_path(boy.id) ,:class => "btn btn-warning btn-xs action-button" %>
	       	<%= link_to "Delete Details", boy ,:method=> :delete, :class => "btn btn-danger btn-xs action-button", data: {:confirm => 'Are you sure?'} %>
	       	</div>
	       	

	      </div>

			<% end %>
      
    </div>
  </div>
</div>

app/views/boys/new.html.erb
<div class="container">
<h1 class = "boy_head"> New Boy </h1>

<%= render :partial => 'form' %>

</div>

app/views/boys/show.html.erb
<div class="container">
<h1 class = "boy_head"> <%= @boy.full_name %> </h1>
<p style="float: right;">

  <a href="<%= new_boy_girl_friend_path(@boy.id) %>" class="btn btn-info btn-sm">
    <span class="glyphicon glyphicon-user"></span> New Girl Friend 
  </a>
</p> 

<p>

  <a href="<%= boys_path() %>" class="btn btn-warning btn-sm">
    <span class="glyphicon glyphicon-user"></span> Boys List
  </a>
</p> 

<div class="col-sm-12" >
	<div class="col-sm-4">
  <img src="<%= @boy.gravatar %>" class="img-rounded" alt="Cinque Terre" width="200" height="200">
  </div>
  <div class="col-sm-8" style="font-size: x-large;">

  	<label>Email:</label><span class="boyspan" ><%= @boy.email %> </span></br>
  	<label>Number of GF:</label> <span class="boyspan"><%= @boy.girl_friends.length %></span>

  </div>

 	

</div>
<div style="float: right;margin-bottom: 15px">
     	<%= link_to "Edit Details", edit_boy_path(@boy.id) ,:class => "btn btn-warning btn-xs" %>
     	<%= link_to "Delete Details", {:action => :destroy, :id=> @boy.id} ,:method=> :delete, :class => "btn btn-danger btn-xs", data: {:confirm => 'Are you sure?'} %>
</div>
<table class="table table-striped table-dark">
  <thead>
    <tr>
      <th scope="col" >#</th>
      <th scope="col" >GF Name</th>
      <th scope="col" >Email</th>
      <th scope="col" >Options</th>
    </tr>
  </thead>
  <tbody>
    
      <% @boy.girl_friends.each do|gf| %>
      <tr>
      	<td style="border-color: #32383e;"> <%= @boy.girl_friends.index(gf) + 1 %> </td>
      	<td style="border-color: #32383e;"> <%= gf.full_name%> </td>
      	<td style="border-color: #32383e;"> <%= gf.email%> </td>
      	<td style="border-color: #32383e;width: 20%;">  
      		<%= link_to "",  boy_girl_friend_path(@boy.id,gf.id) ,:class => "glyphicon glyphicon-eye-open white-icon", :title => "Show Details" %>
	       	<%= link_to "", edit_boy_girl_friend_path(@boy.id,gf.id) ,:class => "glyphicon glyphicon-edit white-icon", :title => "Edit Details" %>
	       	<%= link_to "", [@boy, gf] , :method => :delete, :class => "glyphicon glyphicon-trash white-icon", :title => "Delete Details",  data: {:confirm => 'Are you sure?'} %>

      	</td>
       </tr>
      <% end %>
   
  </tbody>
</table>

</div>

app/views/girl_friends/_form.html.erb
	<%= form_for([@boy, @girl_friend],:html => {:class => "form-horizontal"}) do %>
	    <div class="form-group">
	      <label class="control-label col-sm-2" for="email">First Name:</label>
	      <div class="col-sm-10">
	      	<input type="text" class="form-control" id="first_name" placeholder="Enter First Name" name="girl_friend[first_name]" value="<%= @girl_friend.first_name %>" required>

	      </div>
	    </div>

	    <div class="form-group">
	      <label class="control-label col-sm-2" for="email">Last Name:</label>
	      <div class="col-sm-10">
	      	<input type="text" class="form-control" id="last_name" placeholder="Enter Last Name" name="girl_friend[last_name]" value="<%= @girl_friend.last_name %>" required>
	      </div>
	    </div>

	    <div class="form-group">
	      <label class="control-label col-sm-2" for="pwd">Email:</label>
	      <div class="col-sm-10">          
	        <input type="email" class="form-control" id="email" placeholder="Enter email" name="girl_friend[email]" value="<%= @girl_friend.email %>" required>
	      </div>
	    </div>

	    <div class="form-group">        
	      <div class="col-sm-offset-2 col-sm-10">
	        <button type="submit" class="btn btn-success">Submit</button>
	        <a href="<%= url_for(:back) %>" class="btn btn-danger"> Cancel
				  </a>
	      </div>
	    </div>
<% end %>

app/views/girl_friends/edit.html.erb
<div class="container">
<h1 class = "boy_head"> Edit Girl Friend </h1>

<%= render :partial => 'form' %>

</div>

app/views/girl_friends/new.html.erb
<div class="container">
<h1 class = "boy_head"> New Girl Friend </h1>

<%= render :partial => 'form' %>

</div>

app/views/girl_friends/show.html.erb
<div class="container">
<h1 class = "boy_head"> <%= @girl_friend.full_name %> </h1>

<p>

  <a href="<%= boy_path(@boy.id) %>" class="btn btn-info btn-sm">
    <span class="glyphicon glyphicon-user"></span> Back To Boy
  </a>
</p> 

<div class="col-sm-12" style="margin-bottom: 15px" >
	<div class="col-sm-4">
  <img src="<%= @girl_friend.gravatar %>" class="img-rounded" alt="Cinque Terre" width="200" height="200">
  </div>
  <div class="col-sm-8" style="font-size: x-large;">

  	<label>Email:</label><span class="boyspan" ><%= @girl_friend.email %> </span></br>
  	<label>Belonngs To:</label> <span class="boyspan"><%= @boy.full_name %></span>

  </div>

 	

</div>
<div >
     	<%= link_to "Edit Details", edit_boy_girl_friend_path(@boy.id,@girl_friend.id) ,:class => "btn btn-warning btn-xs" %>
     	<%= link_to "Delete Details", [@boy, @girl_friend], :method=> :delete, :class => "btn btn-danger btn-xs", data: {:confirm => 'Are you sure?'} %>
</div>


</div>

app/views/home/index.html.erb
<div id="overview" class="header">
	<div class="container" >
		<div class="row">
			<div class="col-lg-6 col-md-6">
				<h1>OVERVIEW</h1>
				<p class="text-justify">Demo application which illustrates the basic concepts of RAILS application. We will use boy and his girlfriends relation to understand the concepts. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Let us start learning....</p>

				<%= link_to "SignIn", "#" ,:class => "btn btn-primary btn-md" %>
				<%= link_to "SignUp", "#" ,:class => "btn btn-success btn-md" %>
			</div>
			<div class="col-lg-6 col-md-6">
					<img  src="<%= image_path('b&gf.png') %>"></img>
			</div>
		</div>
	</div>
</div>


<div id="design" class="design">
	<div class="container" >

		<h1>DESIGN</h1>
		<p > Rails model association is shown below. Boy has many girl friends</p>
		<div class="row">
			<div class="col-lg-4 col-md-4" >
				<h4>Boy</h4>
				</br><img  src="<%= image_path('boy.png') %>"></img>
			</div>

			<div class="col-lg-4 col-md-4" style="text-align: center;">
				
				</br>has many<img  src="<%= image_path('arrow.png') %>"></img>
			</div>

			<div class="col-lg-4 col-md-4">
					<h4>Girl Friends</h4>			
					<img  src="<%= image_path('girl.png') %>"></img>
					<img  src="<%= image_path('girl.png') %>"></img></br>
					<img  src="<%= image_path('girl.png') %>"></img>

			</div>
		</div>
	</div>
</div>




<style type="text/css">
	#overview{
		margin-top: 50px;
		background-image:url("<%= image_path('background.jpg') %>");
		background-repeat: no-repeat;
		background-color: #403e3e;
		color: #fff;
		background-size: cover;
		padding: 10px;
	}

	#overview img{
		width: 90%;
		margin: 0 0 0 80px;
	}

	#overview .btn{
		border-radius: 0px;
		padding: 5px 20px;
		margin-left: 40px; 
		margin-top: 10px;
	}

	#overview h1{
		font-weight: bold;
    font-size: 34px;
    margin-bottom: 20px;
	}



	/* DESIGN */

	#design {
		text-align: center;
	}

	#design h1{
		font-weight: bold;
    font-size: 34px;
    margin-bottom: 10px;
	}

	#design h4{
		font-weight: bold;
	}

	#design img{
		width: 20%;
		padding: 15px;
	}




@media(max-width: 768px){
	#overview{
		background-position-x: -400px;
	}

	#overview img {
    width: 100%;
    margin: 0px;
	}
}
	
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js" integrity="sha384-8iPTk2s/jMVj81dnzb/iFR2sdA7u06vHJyyLlAd4snFpCl/SnyUjRrbdJsw1pGIl" crossorigin="anonymous"></script>
  </head>

  <body>
		<nav class="navbar navbar-inverse navbar-fixed-top">

		<div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="<%= root_path %>"><img  src="<%= image_path('b&gf.png') %>"></a>
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#normalNavbar">
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </div>
	    <div id="normalNavbar" class="collapse navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li ><a href="#overview"><i class="fas fa-book"></i></span> Overview</a></li>
					<li ><a href="#design"><i class="fas fa-cogs"></i></span> Design</a></li>		
					<li ><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
					<li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Sign In</a></li>		        
		    </ul>
	    </div>
	  </div>
		</nav>
<% unless notice.blank? %>
	<div class="container-fluid">
<% if notice["status"] == "success" %>
<p class="alert alert-success alert-dismissable fade in" id="notice"> <%= notice["message"] %></p> 
<% else %>
<p class="alert alert-danger alert-dismissable fade in" id="notice"> <%= notice["message"] %></p>
<% end %>
</div>
<% end %>
    <%= yield %>

    <div id="footer" class="footer">
	<div class="container" >
		<div class="row">
			<div class="col-lg-4 col-md-4">
					<h4>Contact</h4>
					<p><i class="fas fa-home"></i> Achamparambath, Elathur, Calicut - 673303</p>		
					<p><i class="fas fa-envelope"></i> sreeyesh009@gmail.com</p>		
					<p><i class="fas fa-phone"></i> +91- 7293852112</p>		
					<p><i class="fas fa-globe"></i> sree.blogspot.com </p>	

			</div>
			<div class="col-lg-4 col-md-4">
					<h4>Copyright</h4>
					<img  src="<%= image_path('sr.png') %>"></img>
			</div>
			<div class="col-lg-4 col-md-4">
					<h4>Connect</h4>
					<i class="social fab fa-facebook-square"></i>
					<i class="social fab fa-google-plus-square"></i>
					<i class="social fab fa-github-square"></i>
					<i class="social fab fa-instagram"></i>
					<i class="social fab fa-youtube-square"></i>

			</div>
		</div>
	</div>
</div>
  </body>
</html>

<style type="text/css">
	body{
		
		/*background-position: center;*/
	}

	.navbar{	
		background-color: #08050c;
		border-color: #08050c;
		border-radius: 0px;
		border-bottom: 0.5px solid white;
	}

	.navbar-brand img{
		max-width:100px; 
		margin-top: -9px;
		max-height: 40px;
	}

	#normalNavbar a{
		color: white;
	}

	#normalNavbar a:hover, a:active{
		color: lightgray;
	}

	/*footer */

	.footer{
		padding: 30px;
		color: #cccccc;
		background-color: #08050c;
	}

	.footer h4{
		font-weight: bold;
		color: white;
		margin-bottom: 15px;
		margin-top: 15px;
	}

	.footer img{
		width:10%;
	}

	.footer .social{
		font-size: 20px;
		height: 30px;
		width: 30px;
		margin-right: 5px;
	}
</style>